# Generated by Django 2.0.5 on 2018-07-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('fabricante', models.CharField(max_length=30, null=True)),
                ('descricao', models.CharField(max_length=30)),
                ('mac', models.CharField(max_length=10)),
                ('ip', models.CharField(max_length=10)),
                ('usuario', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=10)),
                ('local', models.CharField(max_length=10)),
                ('atualizacao', models.DateField(null=True)),
                ('outros', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='ativos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo'),
        ),
    ]
