# Generated by Django 2.0.5 on 2018-07-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ativos',
            name='local',
            field=models.CharField(max_length=20),
        ),
    ]
