# Generated by Django 2.0.5 on 2018-07-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180725_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=8)),
                ('ip', models.CharField(max_length=10)),
                ('root', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=10)),
                ('descricao', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ativos',
            name='outros',
            field=models.TextField(max_length=100),
        ),
    ]
