# Generated by Django 2.0.5 on 2018-07-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180725_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativos',
            name='nome',
        ),
    ]
