# Generated by Django 2.0.5 on 2018-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ativos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='atualizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ativos',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
