# Generated by Django 2.0.5 on 2018-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180725_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='root',
        ),
        migrations.AddField(
            model_name='servidor',
            name='usuario',
            field=models.CharField(default='usuario', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ativos',
            name='fabricante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ativos',
            name='ip',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ip',
            field=models.CharField(max_length=14),
        ),
    ]
