# Generated by Django 2.0.5 on 2018-07-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180726_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('obs', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Servidor',
            new_name='Server',
        ),
    ]
