# Generated by Django 2.0.5 on 2018-08-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180730_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='ip',
            field=models.CharField(max_length=12),
        ),
    ]
